function Hd = Transmitter_LSB_FIR_Coeff_1
%TRANSMITTER_USB_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.6 and Signal Processing Toolbox 8.2.
% Generated on: 15-Apr-2023 13:48:22

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 500000;  % Sampling Frequency

Fstop1 = 48500;           % First Stopband Frequency
Fpass1 = 49500;           % First Passband Frequency
Fpass2 = 50500;           % Second Passband Frequency
Fstop2 = 51000;           % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2]/(Fs/2), [0 1 ...
                          0], [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
