function Hd = Audio_Lowpass_FIR_Coeff
%LOWPASS_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 12-Mar-2023 16:02:53

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 441000;  % Sampling Frequency

Fpass = 40000;           % Passband Frequency
Fstop = 60000;           % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple
Dstop = 0.0001;          % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
